/**
 * The lean default model catalog — the prices the harness starts from before any provider
 * catalog snapshot lands.
 *
 * It lives here rather than in the CLI because the dashboard needs these prices to reprice a
 * turn against a model the router did not pick, and importing `src/cli/main.ts` for a price
 * table would drag Ink, React and 40-odd other modules into a lazily-loaded read-only server.
 * The only dependency is the `Model` type.
 */

import type { Model } from "./types.ts";

export const SEED_MODELS: Model[] = [
  {
    id: "gpt-4o-mini",
    provider: "openai",
    api: "openai-completions",
    name: "GPT-4o mini",
    cost: { input: 0.15, output: 0.6 },
    context_window: 128_000,
    max_tokens: 16_384,
    input: ["text", "image"],
  },
  {
    id: "gpt-4o",
    provider: "openai",
    api: "openai-completions",
    name: "GPT-4o",
    cost: { input: 2.5, output: 10 },
    context_window: 128_000,
    max_tokens: 16_384,
    input: ["text", "image"],
  },
  {
    id: "gpt-5.6-sol",
    provider: "openai",
    api: "openai-completions",
    name: "GPT-5.6 Sol",
    cost: { input: 5.0, output: 30.0, cache_read: 0.5 },
    context_window: 1_050_000,
    max_tokens: 128_000,
    reasoning: true,
    // Verified against the live API: bare + tools 400s, reasoning_effort:"none" + tools is
    // accepted. Without this the whole family is unusable in the agent loop, which always
    // sends tools — and gpt-5.6-luna is in DEFAULT_CANDIDATES, so routing can pick one.
    tools_require_effort_none: true,
    // Also verified live (an image_url part is accepted). supportsImageInput is fail-closed,
    // so leaving this off would have made routing skip the whole family for any turn carrying
    // a pasted screenshot, and the drop-guard discard the image if it was pinned.
    input: ["text", "image"],
  },
  {
    id: "gpt-5.6-terra",
    provider: "openai",
    api: "openai-completions",
    name: "GPT-5.6 Terra",
    cost: { input: 2.5, output: 15.0, cache_read: 0.25 },
    context_window: 1_050_000,
    max_tokens: 128_000,
    reasoning: true,
    tools_require_effort_none: true,
    input: ["text", "image"],
  },
  {
    id: "gpt-5.6-luna",
    provider: "openai",
    api: "openai-completions",
    name: "GPT-5.6 Luna",
    cost: { input: 1.0, output: 6.0, cache_read: 0.1 },
    context_window: 1_050_000,
    max_tokens: 128_000,
    reasoning: true,
    tools_require_effort_none: true,
    input: ["text", "image"],
  },
  {
    // deepseek-chat (V3) is deprecated by DeepSeek effective 2026-07-24; V4 Flash replaces it.
    id: "deepseek-v4-flash",
    provider: "deepseek",
    api: "openai-completions",
    name: "DeepSeek V4 Flash",
    cost: { input: 0.14, output: 0.28, cache_read: 0.0028 },
    context_window: 1_000_000,
    max_tokens: 384_000,
    base_url: "https://api.deepseek.com",
  },
  {
    id: "deepseek-v4-pro",
    provider: "deepseek",
    api: "openai-completions",
    name: "DeepSeek V4 Pro",
    cost: { input: 0.435, output: 0.87 },
    context_window: 1_000_000,
    max_tokens: 384_000,
    reasoning: true,
    base_url: "https://api.deepseek.com",
  },
  {
    id: "grok-4.5",
    provider: "xai",
    api: "openai-completions",
    name: "Grok 4.5",
    cost: { input: 2.0, output: 6.0, cache_read: 0.5 },
    context_window: 500_000,
    max_tokens: 16_384,
    reasoning: true,
    base_url: "https://api.x.ai/v1",
  },
  {
    id: "grok-4.3",
    provider: "xai",
    api: "openai-completions",
    name: "Grok 4.3",
    cost: { input: 1.25, output: 2.5 },
    context_window: 1_000_000,
    max_tokens: 16_384,
    reasoning: true,
    base_url: "https://api.x.ai/v1",
  },
  {
    id: "z-ai/glm-5.2",
    provider: "openrouter",
    api: "openai-completions",
    name: "GLM 5.2",
    cost: { input: 0.82, output: 2.58 },
    context_window: 1_000_000,
    max_tokens: 16_384,
    base_url: "https://openrouter.ai/api/v1",
  },
  {
    id: "moonshotai/kimi-k2.6",
    provider: "openrouter",
    api: "openai-completions",
    name: "Kimi K2.6",
    cost: { input: 0.66, output: 3.41 },
    context_window: 262_144,
    max_tokens: 16_384,
    base_url: "https://openrouter.ai/api/v1",
  },
  {
    id: "minimax/minimax-m3",
    provider: "openrouter",
    api: "openai-completions",
    name: "MiniMax M3",
    cost: { input: 0.098, output: 1.21 },
    context_window: 1_000_000,
    max_tokens: 16_384,
    base_url: "https://openrouter.ai/api/v1",
  },
  {
    id: "claude-haiku-4-5",
    provider: "anthropic",
    api: "anthropic-messages",
    name: "Claude Haiku 4.5",
    cost: { input: 1.0, output: 5.0, cache_read: 0.08, cache_write: 1.25 },
    context_window: 200_000,
    max_tokens: 8192,
    input: ["text", "image"],
    reasoning: false,
  },
  {
    id: "claude-sonnet-4-6",
    provider: "anthropic",
    api: "anthropic-messages",
    name: "Claude Sonnet 4.6",
    cost: { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
    context_window: 200_000,
    max_tokens: 16384,
    input: ["text", "image"],
    reasoning: true,
  },
  {
    id: "claude-opus-4-8",
    provider: "anthropic",
    api: "anthropic-messages",
    name: "Claude Opus 4.8",
    cost: { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
    context_window: 200_000,
    max_tokens: 16384,
    input: ["text", "image"],
    reasoning: true,
    adaptive_thinking: true,
  },
  {
    id: "claude-sonnet-5",
    provider: "anthropic",
    api: "anthropic-messages",
    name: "Claude Sonnet 5",
    cost: { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
    context_window: 1_000_000,
    max_tokens: 128_000,
    input: ["text", "image"],
    reasoning: true,
    adaptive_thinking: true,
  },
  {
    id: "claude-fable-5",
    provider: "anthropic",
    api: "anthropic-messages",
    name: "Claude Fable 5",
    cost: { input: 10.0, output: 50.0, cache_read: 1.0, cache_write: 12.5 },
    context_window: 1_000_000,
    max_tokens: 128_000,
    input: ["text", "image"],
    reasoning: true,
    adaptive_thinking: true,
  },
  {
    // The pool's cheap rung: ~4.4x under gemini-2.5-flash, which was the floor for anyone
    // without a DeepSeek key. `reasoning` is deliberately unset — the reasoning-aware
    // candidate filter then drops it while a thinking level is active, which is the safe
    // direction (a missing rung costs money, an unsupported thinking shape costs the turn).
    id: "gemini-2.5-flash-lite",
    provider: "google",
    api: "google-generative-ai",
    name: "Gemini 2.5 Flash Lite",
    cost: { input: 0.1, output: 0.4, cache_read: 0.01 },
    context_window: 1_048_576,
    max_tokens: 65_536,
    input: ["text", "image"],
  },
  {
    id: "gemini-2.5-flash",
    provider: "google",
    api: "google-generative-ai",
    name: "Gemini 2.5 Flash",
    cost: { input: 0.3, output: 2.5, cache_read: 0.03 },
    context_window: 1_000_000,
    max_tokens: 8192,
    input: ["text", "image"],
    reasoning: true,
  },
  {
    id: "gemini-2.5-pro",
    provider: "google",
    api: "google-generative-ai",
    name: "Gemini 2.5 Pro",
    // Google prices 2.5 Pro in two tiers on prompt size: every rate doubles above 200k.
    cost: {
      input: 1.25,
      output: 10.0,
      cache_read: 0.125,
      long_context: { above_prompt_tokens: 200_000, input: 2.5, output: 15.0, cache_read: 0.25 },
    },
    context_window: 2_000_000,
    max_tokens: 8192,
    input: ["text", "image"],
    reasoning: true,
  },
  {
    id: "gemini-3.6-flash",
    provider: "google",
    api: "google-generative-ai",
    name: "Gemini 3.6 Flash",
    cost: { input: 1.5, output: 7.5, cache_read: 0.15 },
    context_window: 1_048_576,
    max_tokens: 65_536,
    input: ["text", "image"],
    reasoning: true,
  },
];
