"""Curated seed corpus: hand-written, varied-register prompts for task types that
public datasets under-cover. Labels follow the sink-drain map from the research:
rewrite/draft -> creative, explanation -> qa, comparison/advice analysis -> reasoning,
conversational build asks -> code."""

SEEDS: dict[str, list[str]] = {
    "summarization": [
"organize my scattered notes into a clean outline",
        "turn these highlights into flashcard-style key points",
        "consolidate these three drafts into one coherent doc",
        "distill my brainstorm into the five ideas worth keeping",
        "collapse this FAQ into the questions people actually ask",
        "restructure this rambling memo into sections with headers",
"Skim this privacy policy and tell me in a few lines what data they collect.",
        "Give me a two-line summary of each chapter in this report.",
        "Condense this webinar transcript into five key lessons.",
        "Summarize the changes between v2 and v3 of this API from the notes below.",
        "Wrap up this week's standup notes into one short paragraph for the wiki.",
        "Summarize the referee reports into the main revisions requested.",
        "Give me the short version of this insurance claim narrative.",
        "Digest these five articles about the merger into a single briefing note.",
        "Summarize this earnings call transcript in five bullet points for the exec team.",
        "Can you give me the gist of this 40-page PDF? I only care about the pricing changes.",
        "TL;DR this Slack thread, I was on vacation all week.",
        "Condense the attached research paper into an abstract a high schooler could follow.",
        "Boil these customer interviews down to the three recurring complaints.",
        "Write a two-sentence summary of the meeting notes below.",
        "Shorten this blog post to 200 words without losing the main argument.",
        "Give me an executive summary of the incident report.",
        "Recap what happened in chapters 4 through 7 of this novel.",
        "Distill this legal contract into plain-English key obligations.",
        "Sum up the reviewer feedback in a paragraph I can send to the author.",
        "I need a one-paragraph digest of today's AI news items pasted below.",
        "Take these release notes and produce a short changelog customers will actually read.",
        "Compress this podcast transcript into show notes with timestamps.",
        "What are the key takeaways from this quarterly report?",
        "Turn this long email chain into a brief status update for my manager.",
        "Summarize the pros and cons discussed in this forum thread.",
        "Give me the highlights of this 2-hour city council meeting transcript.",
        "Reduce these lecture notes to a one-page revision sheet.",
        "Outline the main plot points of the screenplay draft below.",
        "Write a brief synopsis of this case study for the sales deck.",
        "Condense my dissertation chapter into a conference abstract of 250 words.",
        "Summarize the diff between these two policy versions for the audit log.",
        "Please summarize this Wikipedia article about the Ottoman Empire in 3 paragraphs.",
        "Give me bullet-point notes from this YouTube video transcript.",
        "Digest this 300-comment Reddit thread into the main viewpoints.",
    ],
    "extraction": [
"From the pasted job listings, pull each salary range and location.",
        "Get the case numbers and filing dates out of these court records.",
        "Extract every hex color code used in this CSS file.",
        "List the guests and their arrival times from these RSVP emails.",
        "Pull the part numbers and quantities from this purchase order.",
        "Extract all error codes and their descriptions from the log lines below.",
        "From this bibliography, extract authors, year, and journal for each entry.",
        "Grab the tracking numbers from these shipping notification emails.",
        "Extract the names of all attendees from this Zoom transcript header.",
        "Pull the domain names out of this DNS zone file.",
        "From these product reviews, extract the star rating and the reviewer's country.",
        "Extract the season, episode number, and title from these filenames.",
        "List every chemical compound mentioned in this lab report.",
        "Pull all dollar figures and what they refer to from this budget memo.",
        "Extract the departure and arrival airports from each booking reference below.",
        "From this HTML table, extract the rows as JSON objects.",
        "Extract the license plate numbers mentioned in these incident reports.",
        "Get each speaker's name and title from the conference agenda.",
        "Pull every email address and phone number out of this text dump.",
        "Extract the invoice number, total amount, and due date from this PDF text.",
        "List all the company names mentioned in this article.",
        "From these support tickets, extract the product name and the reported error code.",
        "Get me every date and deadline mentioned in this contract.",
        "Parse out the ingredients and quantities from this recipe blob.",
        "Extract all URLs from the following HTML.",
        "Find every person quoted in this news story and what they said.",
        "Pull the shipping addresses from these order confirmations into a list.",
        "Extract the function names and their arguments from this API documentation.",
        "From this resume, extract education history as structured fields.",
        "Identify all monetary amounts and their currencies in the text below.",
        "Grab the serial numbers from these warranty claims.",
        "Extract speaker names and timestamps from this transcript.",
        "Pull out all the citations from this academic paper into a reference list.",
        "From these tweets, extract hashtags and mentioned users.",
        "Extract the SKU, price, and stock count from each product row below.",
        "List every medication and dosage mentioned in this discharge note.",
        "Find all IP addresses and hostnames in this log excerpt.",
        "Extract the flight numbers, departure times, and gates from this itinerary.",
        "Turn this messy address block into street, city, postcode fields.",
        "Extract all job titles and departments from this org announcement.",
        "From the meeting notes, pull out every action item and its owner.",
        "Extract chapter titles and page numbers from this table of contents.",
    ],
    "classification": [
"Read each app store review and label it feature request, bug report, or praise.",
        "Tag each of these emails urgent or not urgent.",
        "For every headline below, decide whether it's satire or real news.",
        "Label each customer chat as resolved, escalated, or abandoned.",
        "Classify each of these product descriptions by department: electronics, apparel, home, toys.",
        "Mark every sentence in this essay as thesis, evidence, or filler.",
        "Rate the toxicity of each comment: none, mild, severe.",
        "Decide for each patent abstract whether it's software, hardware, or biotech.",
        "Label these song lyrics by mood: upbeat, melancholy, angry, romantic.",
        "Classify each incident ticket by root cause: config, code, hardware, human error.",
        "For each of these ads, label the target audience: teens, parents, seniors, professionals.",
        "Tag every recipe below as vegetarian, vegan, or neither.",
        "Sort these quotes into motivational, humorous, or philosophical.",
        "Determine whether each contract clause is standard boilerplate or unusual.",
        "Label each of these support tickets as billing, technical, or account.",
        "Is this email spam or not? Explain nothing, just the label.",
        "Categorize these product reviews as positive, negative, or mixed.",
        "Tag each news headline below with its topic: politics, sports, tech, or business.",
        "Which of these tweets express anger? Mark each one angry or calm.",
        "Sort these job applications into engineering, design, and marketing piles.",
        "Classify the sentiment of each customer comment on a 1-5 scale.",
        "Decide for each transaction whether it looks fraudulent or legitimate.",
        "Label these forum posts as question, answer, or discussion.",
        "Assign each of these bugs a severity: critical, major, minor.",
        "Categorize my expenses below into travel, meals, software, and office.",
        "Is the following movie review a rave, a pan, or lukewarm?",
        "Classify each sentence as fact or opinion.",
        "Bucket these survey responses into promoters, passives, and detractors.",
        "Mark each of these URLs as safe, suspicious, or malicious.",
        "Determine whether each headline is clickbait or straight news.",
        "Label the language of each of these snippets.",
        "Classify these images' alt-text descriptions as product, lifestyle, or logo.",
        "Triage the following error logs into infra, application, or user error.",
        "Decide if each of these messages violates our community guidelines.",
        "Categorize the following books by genre.",
        "Which category does each grocery item belong to: produce, dairy, pantry, frozen?",
    ],
    "creative": [
"help me phrase this feedback so it doesn't sting",
        "make this bio sound warmer",
        "name ideas for a sourdough bakery",
        "brainstorm titles for my podcast about urban farming",
        "suggest names for a black kitten with white paws",
        "make this product update sound exciting",
        "soften this reminder email to a late client",
        "punch up the opening line of my talk",
        "give this newsletter subject line more energy",
        "help me word an out-of-office that's professional but fun",
        "come up with a team name for our trivia group",
        "rewrite this bullet list as a smooth paragraph",
"Write a limerick about a cat who thinks it owns the house.",
        "Draft a mission statement for a co-op grocery that doesn't sound corporate.",
        "Turn this list of features into a story-driven product launch email.",
        "Write the villain's monologue for a heist movie set in a museum.",
        "Compose a toast for my parents' 40th anniversary.",
        "Rewrite this paragraph so it reads like a nature documentary narration.",
        "Invent a founding legend for a fictional mountain town.",
        "Write three taglines for a zero-waste coffee shop.",
        "Draft an artist statement for my abstract photography exhibit.",
        "Write a eulogy for a beloved neighborhood bookstore that's closing.",
        "Create a jingle for a local plumbing company, four lines max.",
        "Rewrite my resume summary to sound confident but not arrogant.",
        "Write a monologue from the perspective of the last payphone in the city.",
        "Draft the welcome speech for our small film festival.",
        "Turn these customer quotes into a warm testimonial paragraph.",
        "Write a scene where two old friends argue about selling the family farm.",
        "Rewrite this email to sound more professional but still friendly.",
        "Draft a cover letter for a senior data analyst role at a fintech startup.",
        "Write a short story about a lighthouse keeper who finds a message in a bottle.",
        "Punch up this LinkedIn post so it doesn't sound like a press release.",
        "Compose a birthday poem for my grandmother who loves gardening.",
        "Write product copy for a minimalist standing desk, 3 variants.",
        "Draft a wedding toast for my best friend, funny but heartfelt.",
        "Rewrite this paragraph in the style of a hard-boiled detective novel.",
        "I need a catchy tagline for a dog-walking app.",
        "Write the opening scene of a sci-fi screenplay set on a generation ship.",
        "Make this apology email to a customer sound sincere, not corporate.",
        "Draft a newsletter intro about our spring product launch.",
        "Write song lyrics about leaving a small town for the city.",
        "Turn these dry bullet points into an engaging conference talk abstract.",
        "Rewrite my dating profile bio to be wittier.",
        "Compose a haiku about morning coffee.",
        "Write a persuasive fundraising letter for a local animal shelter.",
        "Draft the About Us page for a family-run bakery.",
        "Give me five creative Instagram captions for this beach photo.",
        "Write a bedtime story about a dragon who is afraid of the dark.",
        "Rephrase this rejection letter to be kinder while staying firm.",
        "Draft a speech for a retirement party for a teacher of 30 years.",
        "Write flavor text for a fantasy card game about a cursed mirror.",
        "Turn my rough notes into a polished blog post about remote work.",
        "Rewrite this technical announcement for a non-technical audience.",
        "Ghost-write a thank-you note to my mentor.",
    ],
    "qa": [
"explain how a 401k works",
        "what's the difference between RAM and storage",
        "why do leaves change color in the fall",
        "how does wifi actually reach my phone",
        "explain interest rates like I'm new to this",
        "what's the deal with electric car batteries degrading",
        "why is the ocean salty",
        "how do credit cards make money",
        "what happens when you delete a file",
        "explain how airplanes stay up",
        "what's the difference between soccer and football rules",
        "why do we dream",
        "how does a dishwasher clean better than hand washing",
        "explain what APR means on a loan",
        "what's the difference between whiskey and bourbon",
        "why does my phone battery die faster in winter",
        "how do search engines decide what comes first",
        "what is gluten and why do some people avoid it",
        "suggest a good beginner camera and explain why",
        "what should I know before adopting a rescue dog",
        "Explain how a heat pump works and why it's more efficient than a furnace.",
        "What's the difference between a Roth IRA and a traditional IRA?",
        "Why is the sky blue during the day but red at sunset?",
        "Explain quantum entanglement like I'm twelve.",
        "How does compound interest actually work?",
        "What causes inflation and who benefits from it?",
        "Walk me through how vaccines train the immune system.",
        "Why do some countries drive on the left?",
        "Explain what happens during a solar eclipse.",
        "How do noise-cancelling headphones work?",
        "What's the deal with daylight saving time — why do we still do it?",
        "Explain the difference between weather and climate.",
        "How is olive oil graded, and what does extra virgin mean?",
        "Why can't we just print more money to pay off national debt?",
        "What does it mean when the Fed raises interest rates?",
        "Explain how DNS resolves a website name to an address.",
        "Why do airplanes leave white trails in the sky?",
        "What's the difference between bail and bond?",
        "How do bees decide where to build a hive?",
        "Explain the electoral college in plain terms.",
    ],
    "reasoning": [
"help me plan a birthday party for 20 kids on a budget",
        "which phone should I upgrade to, I mostly take photos",
        "give me honest feedback on my pricing strategy",
        "help me decide between these two apartment options",
        "plan my training schedule for a half marathon in 12 weeks",
        "what's the best order to visit these 5 cities by train",
        "help me figure out if freelancing full time makes sense",
        "which credit card fits my spending, mostly groceries and travel",
        "map out a savings plan to hit 20k in two years",
        "advise me on whether to repair or replace my 12 year old car",
        "Should I lease or buy a car if I drive 25k miles a year? Walk through the math.",
        "Compare living in Austin vs Denver for a remote software engineer with two kids.",
        "Which is the better deal: a 15-year mortgage at 5.1% or 30-year at 5.8%? Reason it out.",
        "Help me think through whether to take the job offer with more pay but worse equity.",
        "My startup has 8 months of runway. Should we raise now or cut burn? Lay out the tradeoffs.",
        "Compare PostgreSQL and DynamoDB for an event-sourced ordering system under spiky load.",
        "Is it smarter to pay off my 6% student loans or invest in index funds? Show the reasoning.",
        "Plan the seating for a 12-person dinner where three pairs of guests can't sit together.",
        "A train leaves at 3pm going 80 km/h; another at 4pm going 110 km/h. When does the second catch up?",
        "Weigh the pros and cons of microservices vs a modular monolith for a 6-person team.",
        "If I flip a fair coin five times, what's the probability of at least two heads? Explain.",
        "Should our family of four get the annual theme park pass or pay per visit? We might go 5 times.",
        "Analyze whether it's worth switching from AWS to a bare-metal provider at our scale.",
        "Compare the total cost of ownership of an EV vs a hybrid over 8 years in a cold climate.",
        "Decide the optimal order to pay down these four debts and justify the strategy.",
        "Three friends split a bill with a coupon and unequal orders — figure out who owes what.",
        "Evaluate whether our SaaS should move from per-seat to usage-based pricing.",
        "Which apartment should I pick: cheaper with a 50-minute commute, or pricier 10 minutes away?",
        "Reason through whether a 4-day work week would raise or lower our team's output.",
        "Given these symptoms and constraints, which project management method fits our team best?",
    ],
    "code": [
"why doesn't my program compile, error log below",
        "the tests in this repo keep failing, figure out why",
        "debug this stack trace for me",
        "my script crashes with a segfault, here's the code",
        "refactor this function so it's actually readable",
        "explain what this regex does and simplify it",
        "the build passes locally but fails in CI, investigate",
        "there's a memory leak somewhere in this service, find it",
        "add error handling to this endpoint",
        "why is this query so slow, here's the schema",
        "convert this callback code to async await",
        "the login form throws a 500 on submit, fix it",
        "write unit tests for the parser module",
        "this loop is off by one somewhere, spot it",
        "migrate this component from class to hooks",
        "my docker container exits immediately, diagnose it",
        "clean up the linter warnings in this file",
        "the app works in chrome but breaks in safari, why",
        "optimize this function, it's called a million times",
        "hook up the payment webhook to update order status",
        "Make me a simple app to track my workouts.",
        "Create a landing page with a signup form for my newsletter.",
        "I want an online store for my handmade candles, set it up.",
        "Build a portfolio site for my photography, dark theme.",
        "Set up a blog where I can post recipes with photos.",
        "Make a Chrome extension that hides YouTube comments.",
        "Create a Discord bot that welcomes new members.",
        "I need a booking page where clients can pick a time slot with me.",
        "Build a dashboard showing our sales numbers from this spreadsheet.",
        "Write a script that renames all my vacation photos by date.",
        "Automate downloading my bank statements every month.",
        "Make a tool that converts CSV files to pretty HTML tables.",
        "Set up a Telegram bot that sends me the weather every morning.",
        "Create a countdown timer page for our product launch.",
        "Build a quiz app for my classroom with a leaderboard.",
        "I want a personal finance tracker with charts, can you build it?",
        "Make my restaurant a menu page with prices I can edit easily.",
        "Fix my landing page, the hero image overlaps the text on mobile.",
        "Add a dark mode toggle to my existing site.",
    ],
    "tool_use": [
        "Book me a table for two at an Italian place near the office on Friday at 7.",
        "Add milk, eggs, and coffee beans to my shopping list.",
        "Schedule a 30-minute sync with the design team next Tuesday morning.",
        "Set a reminder to renew my passport in March.",
        "Send the Q3 deck to the leadership channel at 9am tomorrow.",
        "Cancel my 2pm and move the dentist appointment to Thursday.",
        "Order another box of the printer paper we got last time.",
        "Turn off the living room lights and set the thermostat to 68.",
        "Play my focus playlist and silence notifications for two hours.",
        "File an expense for the client dinner receipt I just uploaded.",
        "Create a Jira ticket for the login timeout bug and assign it to Priya.",
        "Text my wife that I'll be 20 minutes late.",
        "Find the cheapest nonstop flight to Chicago next weekend and hold it.",
        "Start a timer for 25 minutes.",
        "Add this article to my read-later list.",
        "Open a pull request with these changes and request review from the platform team.",
    ],
    "translation": [
        "Translate this product description into French and German.",
        "How do you say 'where is the nearest pharmacy' in Japanese?",
        "Translate my grandmother's letter from Polish to English, keep the tone.",
        "Localize this error message into Spanish, Portuguese, and Italian.",
        "Translate the chorus of this song from Korean to English.",
        "Convert this legal disclaimer into simplified Chinese.",
        "Translate this restaurant menu from Thai to English.",
        "What's the German word for the feeling of wanting to be alone?",
        "Translate our onboarding email into Hindi without sounding stiff.",
        "Render this medieval Latin inscription into modern English.",
        "Translate these UI strings to Arabic and flag any that will overflow.",
        "Say 'thank you for your hospitality' in Turkish, formal register.",
        "Translate this WhatsApp conversation from Brazilian Portuguese.",
        "Put this safety notice into Vietnamese and Tagalog.",
    ],
    "rag": [
"Given the wiki pages pasted below, when was the bridge actually completed?",
        "Answer using only the provided excerpts: what triggers the circuit breaker in this system?",
        "Based on the terms of service above, can users export their data after cancellation?",
        "From the pasted changelog entries, which release introduced the rate limiter?",
        "Using the context documents, list the prerequisites for the certification exam.",
        "Per the attached lease agreement, who is responsible for appliance repairs?",
        "According to the onboarding guide above, what accounts do new hires get by default?",
        "From the grant proposal text provided, what is the total requested budget?",
        "Based on these API docs, what does error code 4092 mean and how do I recover?",
        "Using the syllabus below, which weeks cover thermodynamics?",
        "Answer strictly from the given financial statements: what was the operating margin?",
        "According to the pasted troubleshooting guide, what should I check before replacing the pump?",
        "From the provided clinical guidelines, what is the recommended dosage for adults over 65?",
        "Based on the meeting transcript above, who volunteered to own the migration?",
        "Using the provided style guide, how should we capitalize product names in headings?",
        "Per the security policy document, how often must access reviews happen?",
        "From these customer emails, what date did the outage reportedly start?",
        "According to the manual excerpt, what does the blinking amber light indicate?",
        "Answer from the given research abstracts only: which study had the largest sample size?",
        "Based on the pasted itinerary, how long is the layover in Doha?",
        "Using the FAQ content above, is there a fee for early withdrawal?",
        "From the codebase README provided, what environment variables are required to boot?",
        "Using the attached policy documents, what is our parental leave allowance?",
        "Based on the knowledge base articles below, how do I rotate the API keys?",
        "According to these meeting minutes, what did we decide about the vendor contract?",
        "From the documentation provided, explain how to configure SSO with Okta.",
        "Answer from the context only: what were the side effects reported in the trial?",
        "Given these three support articles, why would the sync fail on mobile?",
        "Using the employee handbook excerpt, can I carry over unused vacation days?",
        "Based on the product spec below, does the device support USB-C charging?",
        "From these earnings transcripts, what guidance did management give for Q4?",
        "Consult the attached runbook and tell me the rollback steps for a bad deploy.",
        "According to this insurance policy text, is water damage from a burst pipe covered?",
        "Using only the provided court filings, summarize the plaintiff's main claim.",
    ],
    "other": [
"act as a medieval innkeeper and greet me",
        "pretend to be a grumpy weather forecaster",
        "roleplay a job interview where you're the candidate",
        "be my improv partner, we're stranded on the moon",
        "act like a 1920s radio announcer for this game recap",
        "pretend you're my personal trainer yelling encouragement",
        "let's play twenty questions",
        "you be the dungeon master, I'm a rogue",
        "act as a french waiter taking my order",
        "pretend to interview me like a talk show host",
        "speak like shakespeare for the rest of this chat",
        "be a devil's advocate against my plan",
        "hey how's it going",
        "good morning!",
        "thanks, that was helpful",
        "lol that's actually funny",
        "are you a real person?",
        "what should we talk about",
        "tell me something interesting",
        "I'm bored",
        "never mind, forget it",
        "ok sounds good",
        "wow",
        "can you keep a secret",
        "what do you think about me",
        "let's play a game",
        "sing me something",
        "do you ever get tired",
    ],
}
