"""Curated seed corpus: hand-written, varied-register prompts for task types that
public datasets under-cover. Labels follow the sink-drain map from the research:
rewrite/draft -> creative, explanation -> qa, comparison/advice analysis -> reasoning,
conversational build asks -> code."""

SEEDS: dict[str, list[str]] = {
    "summarization": [
"give me the hallway version of this proposal",
        "what does this memo actually commit us to, in brief",
        "compress my long cover note down to a third",
        "what did the quarterly review actually conclude, two lines",
"trim this bloated report into just the decisions",
        "cut these meeting minutes down to action items and owners",
        "boil the retro notes down to what we're changing",
        "collapse this thread into who owes what by when",
"give me the elevator pitch version of this business plan",
        "what does this inspection report actually say about the roof, briefly",
        "what did the board memo actually decide, one paragraph",
        "cut my rambling draft down to its actual point",
        "shrink this 3000 word essay to a tight 500",
        "give me the too-long-didn't-read of this policy change",
        "condense my long apology email before I overshare",
        "what's the short version of this study's findings",
"collapse this week's incident channel into a two-paragraph recap",
        "summarize the peer reviews into what I actually need to change",
        "give me the one-breath version of this insurance renewal letter",
        "condense these conference notes into five takeaways for the team",
        "summarize the tenant's complaint history for the hearing",
        "boil this vendor comparison down to a recommendation memo",
        "recap the season finale discussion thread without spoilers for ep 9",
        "shrink this onboarding doc into a first-day checklist",
        "summarize what changed between the two contract drafts",
        "digest these five bug reports into one engineering ticket",
"organize my scattered notes into a clean outline",
        "turn these highlights into flashcard-style key points",
        "consolidate these three drafts into one coherent doc",
        "distill my brainstorm into the five ideas worth keeping",
        "collapse this FAQ into the questions people actually ask",
        "restructure this rambling memo into sections with headers",
"Skim this privacy policy and tell me in a few lines what data they collect.",
        "Give me a two-line summary of each chapter in this report.",
        "Condense this webinar transcript into five key lessons.",
        "Summarize the changes between v2 and v3 of this API from the notes below.",
        "Wrap up this week's standup notes into one short paragraph for the wiki.",
        "Summarize the referee reports into the main revisions requested.",
        "Give me the short version of this insurance claim narrative.",
        "Digest these five articles about the merger into a single briefing note.",
        "Summarize this earnings call transcript in five bullet points for the exec team.",
        "Can you give me the gist of this 40-page PDF? I only care about the pricing changes.",
        "TL;DR this Slack thread, I was on vacation all week.",
        "Condense the attached research paper into an abstract a high schooler could follow.",
        "Boil these customer interviews down to the three recurring complaints.",
        "Write a two-sentence summary of the meeting notes below.",
        "Shorten this blog post to 200 words without losing the main argument.",
        "Give me an executive summary of the incident report.",
        "Recap what happened in chapters 4 through 7 of this novel.",
        "Distill this legal contract into plain-English key obligations.",
        "Sum up the reviewer feedback in a paragraph I can send to the author.",
        "I need a one-paragraph digest of today's AI news items pasted below.",
        "Take these release notes and produce a short changelog customers will actually read.",
        "Compress this podcast transcript into show notes with timestamps.",
        "What are the key takeaways from this quarterly report?",
        "Turn this long email chain into a brief status update for my manager.",
        "Summarize the pros and cons discussed in this forum thread.",
        "Give me the highlights of this 2-hour city council meeting transcript.",
        "Reduce these lecture notes to a one-page revision sheet.",
        "Outline the main plot points of the screenplay draft below.",
        "Write a brief synopsis of this case study for the sales deck.",
        "Condense my dissertation chapter into a conference abstract of 250 words.",
        "Summarize the diff between these two policy versions for the audit log.",
        "Please summarize this Wikipedia article about the Ottoman Empire in 3 paragraphs.",
        "Give me bullet-point notes from this YouTube video transcript.",
        "Digest this 300-comment Reddit thread into the main viewpoints.",
    ],
    "extraction": [
"list every endpoint and method from this API reference",
        "pull the required auth scopes for each route from these docs",
        "extract the config keys and defaults from this reference page",
"pull each warranty period and coverage limit from these product manuals",
        "extract the sender, subject, and date from this email header dump",
        "list the ticket numbers and priorities from this sprint export",
        "grab all the ISBNs from this catalog page",
        "extract each property's square footage and asking price from the listings",
        "get the batch numbers and expiry dates off these labels",
        "pull the citation numbers and fine amounts from these parking tickets",
        "extract every timestamped event from this security log",
        "list each grant's award amount and deadline from the announcements",
        "pull the VINs and mileage from these vehicle records",
        "extract the committee names and their chairs from the org minutes",
        "grab each podcast guest and episode number from the feed",
        "pull the alt titles and runtimes from this film festival program",
        "extract all the postal codes from these delivery manifests",
        "list every referenced statute from this legal brief",
        "get the room numbers and capacities from the venue map text",
        "extract each employee's start date from these offer letters",
        "pull the currency pairs and rates from this trading summary",
        "extract the version numbers and release dates from this changelog",
        "list all hashtags and their counts from this analytics export",
        "pull each ingredient's allergen flags from these labels",
        "extract the station names and departure times from the timetable",
        "get every DOI from these journal references",
        "pull the plot numbers and owners from the cemetery registry text",
        "extract the license classes and endorsements from these DMV records",
        "list the paint codes and finish types from the work order",
        "extract each donor tier and perk from the campaign page",
        "pull the seat assignments from these boarding passes",
        "get all the file paths mentioned in this stack trace",
        "extract the policy numbers and premiums from these renewal notices",
        "pull each city and its population from the almanac excerpt",
        "extract the course codes and credit hours from this transcript",
        "list every API key name (not value) referenced in this config",
        "pull the tail numbers and aircraft types from the flight log",
        "extract each song title and duration from the setlist",
        "get the case citations and outcomes from these summaries",
        "pull the model years and trims from these classified ads",
        "extract every mentioned vitamin and dosage from the supplement panel",
"From the pasted job listings, pull each salary range and location.",
        "Get the case numbers and filing dates out of these court records.",
        "Extract every hex color code used in this CSS file.",
        "List the guests and their arrival times from these RSVP emails.",
        "Pull the part numbers and quantities from this purchase order.",
        "Extract all error codes and their descriptions from the log lines below.",
        "From this bibliography, extract authors, year, and journal for each entry.",
        "Grab the tracking numbers from these shipping notification emails.",
        "Extract the names of all attendees from this Zoom transcript header.",
        "Pull the domain names out of this DNS zone file.",
        "From these product reviews, extract the star rating and the reviewer's country.",
        "Extract the season, episode number, and title from these filenames.",
        "List every chemical compound mentioned in this lab report.",
        "Pull all dollar figures and what they refer to from this budget memo.",
        "Extract the departure and arrival airports from each booking reference below.",
        "From this HTML table, extract the rows as JSON objects.",
        "Extract the license plate numbers mentioned in these incident reports.",
        "Get each speaker's name and title from the conference agenda.",
        "Pull every email address and phone number out of this text dump.",
        "Extract the invoice number, total amount, and due date from this PDF text.",
        "List all the company names mentioned in this article.",
        "From these support tickets, extract the product name and the reported error code.",
        "Get me every date and deadline mentioned in this contract.",
        "Parse out the ingredients and quantities from this recipe blob.",
        "Extract all URLs from the following HTML.",
        "Find every person quoted in this news story and what they said.",
        "Pull the shipping addresses from these order confirmations into a list.",
        "Extract the function names and their arguments from this API documentation.",
        "From this resume, extract education history as structured fields.",
        "Identify all monetary amounts and their currencies in the text below.",
        "Grab the serial numbers from these warranty claims.",
        "Extract speaker names and timestamps from this transcript.",
        "Pull out all the citations from this academic paper into a reference list.",
        "From these tweets, extract hashtags and mentioned users.",
        "Extract the SKU, price, and stock count from each product row below.",
        "List every medication and dosage mentioned in this discharge note.",
        "Find all IP addresses and hostnames in this log excerpt.",
        "Extract the flight numbers, departure times, and gates from this itinerary.",
        "Turn this messy address block into street, city, postcode fields.",
        "Extract all job titles and departments from this org announcement.",
        "From the meeting notes, pull out every action item and its owner.",
        "Extract chapter titles and page numbers from this table of contents.",
    ],
    "classification": [
"sort these invoices into paid and overdue",
        "sort incoming resumes into yes, no, and maybe",
        "decide for each image caption whether it's ad or editorial",
        "bucket the log lines by severity level",
        "sort these emails into internal and external senders",
"group these stack traces by failing service",
        "sort these crash reports by platform",
"sort these receipts into reimbursable and personal",
        "tag every sentence as claim, evidence, or opinion",
        "bucket these customer emails by product line",
        "sort the headlines into markets, politics, and culture",
        "tag each error message as retryable or fatal",
        "sort these applicants into interview, hold, and reject",
        "tag the incoming tickets by team: infra, app, or data",
        "sort my bookmarks into work, learning, and fun",
"label each refund request as approve, deny, or escalate",
        "tag these commit messages as breaking, feature, or docs",
        "sort these leads into hot, warm, and cold",
        "classify each meal photo description as breakfast, lunch, or dinner",
        "mark each clause as favorable, neutral, or risky for us",
        "bucket these podcasts by format: interview, panel, or narrative",
        "label these workout logs as cardio, strength, or mobility",
        "grade each translation as fluent, understandable, or broken",
        "categorize the returns by reason: fit, damage, or changed mind",
        "tag each screenshot description as bug, feature request, or question",
        "sort these grant applications by stage: draft, submitted, funded",
        "classify each review as verified purchase or not",
        "label these road reports as clear, slow, or closed",
        "mark each password in this audit as strong, weak, or reused",
        "bucket the feedback into praise, complaint, and suggestion",
        "classify each sensor reading as normal, warning, or critical",
        "tag these listings as new, used, or refurbished",
        "sort the applicants by visa status category from their notes",
        "label the calls as sales, support, or spam",
        "categorize each expense line as capex or opex",
"Read each app store review and label it feature request, bug report, or praise.",
        "Tag each of these emails urgent or not urgent.",
        "For every headline below, decide whether it's satire or real news.",
        "Label each customer chat as resolved, escalated, or abandoned.",
        "Classify each of these product descriptions by department: electronics, apparel, home, toys.",
        "Mark every sentence in this essay as thesis, evidence, or filler.",
        "Rate the toxicity of each comment: none, mild, severe.",
        "Decide for each patent abstract whether it's software, hardware, or biotech.",
        "Label these song lyrics by mood: upbeat, melancholy, angry, romantic.",
        "Classify each incident ticket by root cause: config, code, hardware, human error.",
        "For each of these ads, label the target audience: teens, parents, seniors, professionals.",
        "Tag every recipe below as vegetarian, vegan, or neither.",
        "Sort these quotes into motivational, humorous, or philosophical.",
        "Determine whether each contract clause is standard boilerplate or unusual.",
        "Label each of these support tickets as billing, technical, or account.",
        "Is this email spam or not? Explain nothing, just the label.",
        "Categorize these product reviews as positive, negative, or mixed.",
        "Tag each news headline below with its topic: politics, sports, tech, or business.",
        "Which of these tweets express anger? Mark each one angry or calm.",
        "Sort these job applications into engineering, design, and marketing piles.",
        "Classify the sentiment of each customer comment on a 1-5 scale.",
        "Decide for each transaction whether it looks fraudulent or legitimate.",
        "Label these forum posts as question, answer, or discussion.",
        "Assign each of these bugs a severity: critical, major, minor.",
        "Categorize my expenses below into travel, meals, software, and office.",
        "Is the following movie review a rave, a pan, or lukewarm?",
        "Classify each sentence as fact or opinion.",
        "Bucket these survey responses into promoters, passives, and detractors.",
        "Mark each of these URLs as safe, suspicious, or malicious.",
        "Determine whether each headline is clickbait or straight news.",
        "Label the language of each of these snippets.",
        "Classify these images' alt-text descriptions as product, lifestyle, or logo.",
        "Triage the following error logs into infra, application, or user error.",
        "Decide if each of these messages violates our community guidelines.",
        "Categorize the following books by genre.",
        "Which category does each grocery item belong to: produce, dairy, pantry, frozen?",
    ],
    "creative": [
"help me name my hamster, something noble",
        "name my new kitten, greek mythology style",
        "make this update sound friendlier",
        "make the invite wording friendlier",
"make this memo friendlier",
        "make the payment reminder sound gentler",
        "make this notice less scary for parents",
        "make my bio warmer without being cheesy",
        "help me name my goldfish, something dramatic",
        "name ideas for a rescue beagle",
        "help me name our wifi network, make it funny",
        "soften this announcement about the office move",
"write a fortune cookie message about patience",
        "give me a limerick about my cat knocking things over",
        "draft the invitation copy for a backyard movie night",
        "name my fantasy football team, pun preferred",
        "write a yearbook quote that's funny but not cringe",
        "compose a short villanelle about the last train home",
        "make my out-of-office reply sound like a nature documentary",
        "write the back-cover blurb for my cozy mystery draft",
        "brainstorm slogans for a bike repair co-op",
        "draft a knock-knock joke about spreadsheets",
        "write wedding vows that mention our terrible first date",
        "give my food truck a name and a one-line pitch",
        "write a haiku about deadlines",
        "punch up this birthday card message for my boss",
        "draft an apology poem to my neighbor about the leaf blower",
        "write a tagline for our escape room's pirate theme",
        "compose a lullaby verse about rain on the roof",
        "make this bake sale flyer copy irresistible",
        "write a roast joke about my brother's fishing skills",
        "draft the opening lines of a heist novel set in a library",
        "give me alt text with personality for this product shot",
        "write a six-word story about moving out",
        "script a 15-second radio spot for a farmers market",
        "rename these boring menu items to sound delicious",
        "write a clever 404 page message for a travel site",
        "draft a friendly nudge to the group chat about splitting the cabin cost",
        "write an acrostic poem for the name MARIA",
        "make up a bedtime story where the moon loses its keys",
        "give this newsletter section a wittier header",
        "write a toast for my coworker's last day",
        "draft a personals-style ad for my old couch",
        "compose a cheer for a kids soccer team called the Rockets",
        "rewrite these safety instructions as a sea shanty",
        "write a museum placard for my kid's macaroni art",
        "give me three metaphors for procrastination",
        "draft a warm welcome message for new forum members",
        "write the fortune teller's lines for our halloween booth",
        "make a silly oath for our board game night league",
        "write a haggling scene between a robot and a fruit vendor",
        "compose a two-line eulogy for my dead houseplant",
        "draft a graduation caption for my little sister",
        "write the hold-music announcement nobody will hate",
        "give my podcast episode a title that isn't clickbait",
        "write a friendly rejection for a timeshare pitch",
        "draft a note to my future self for new year's",
        "turn this recipe intro into a tiny memoir",
        "write banter for two mascots arguing at halftime",
        "compose a short ode to the office coffee machine",
"help me phrase this feedback so it doesn't sting",
        "make this bio sound warmer",
        "name ideas for a sourdough bakery",
        "brainstorm titles for my podcast about urban farming",
        "suggest names for a black kitten with white paws",
        "make this product update sound exciting",
        "soften this reminder email to a late client",
        "punch up the opening line of my talk",
        "give this newsletter subject line more energy",
        "help me word an out-of-office that's professional but fun",
        "come up with a team name for our trivia group",
        "rewrite this bullet list as a smooth paragraph",
"Write a limerick about a cat who thinks it owns the house.",
        "Draft a mission statement for a co-op grocery that doesn't sound corporate.",
        "Turn this list of features into a story-driven product launch email.",
        "Write the villain's monologue for a heist movie set in a museum.",
        "Compose a toast for my parents' 40th anniversary.",
        "Rewrite this paragraph so it reads like a nature documentary narration.",
        "Invent a founding legend for a fictional mountain town.",
        "Write three taglines for a zero-waste coffee shop.",
        "Draft an artist statement for my abstract photography exhibit.",
        "Write a eulogy for a beloved neighborhood bookstore that's closing.",
        "Create a jingle for a local plumbing company, four lines max.",
        "Rewrite my resume summary to sound confident but not arrogant.",
        "Write a monologue from the perspective of the last payphone in the city.",
        "Draft the welcome speech for our small film festival.",
        "Turn these customer quotes into a warm testimonial paragraph.",
        "Write a scene where two old friends argue about selling the family farm.",
        "Rewrite this email to sound more professional but still friendly.",
        "Draft a cover letter for a senior data analyst role at a fintech startup.",
        "Write a short story about a lighthouse keeper who finds a message in a bottle.",
        "Punch up this LinkedIn post so it doesn't sound like a press release.",
        "Compose a birthday poem for my grandmother who loves gardening.",
        "Write product copy for a minimalist standing desk, 3 variants.",
        "Draft a wedding toast for my best friend, funny but heartfelt.",
        "Rewrite this paragraph in the style of a hard-boiled detective novel.",
        "I need a catchy tagline for a dog-walking app.",
        "Write the opening scene of a sci-fi screenplay set on a generation ship.",
        "Make this apology email to a customer sound sincere, not corporate.",
        "Draft a newsletter intro about our spring product launch.",
        "Write song lyrics about leaving a small town for the city.",
        "Turn these dry bullet points into an engaging conference talk abstract.",
        "Rewrite my dating profile bio to be wittier.",
        "Compose a haiku about morning coffee.",
        "Write a persuasive fundraising letter for a local animal shelter.",
        "Draft the About Us page for a family-run bakery.",
        "Give me five creative Instagram captions for this beach photo.",
        "Write a bedtime story about a dragon who is afraid of the dark.",
        "Rephrase this rejection letter to be kinder while staying firm.",
        "Draft a speech for a retirement party for a teacher of 30 years.",
        "Write flavor text for a fantasy card game about a cursed mirror.",
        "Turn my rough notes into a polished blog post about remote work.",
        "Rewrite this technical announcement for a non-technical audience.",
        "Ghost-write a thank-you note to my mentor.",
    ],
    "qa": [
"why do cats sleep so much",
        "why do dogs chase their tails",
        "explain the stock market to my uncle",
        "explain wifi to my grandma",
"why do dogs tilt their heads",
        "why do cats knead blankets",
        "why do we yawn when others yawn",
        "why do onions sprout in the pantry",
        "explain crypto to my mom",
        "explain NFTs like I'm five",
        "explain the cloud to my grandpa",
        "explain inflation to a teenager",
"how do solar panels perform on cloudy days",
        "how is maple syrup made",
        "how do electric kettles boil so fast",
        "how does laser eye surgery actually work",
        "how do banks decide mortgage rates",
        "how is cheese aged",
        "how do heat exchangers work in simple terms",
        "how does a septic system handle winter",
"why do onions make you cry",
        "what's the deal with airplane mode, does it matter",
        "how do casinos always come out ahead",
        "why is the first pancake always bad",
        "what happens to a package marked return to sender",
        "why do some medicines say take with food",
        "how does a car lease buyout work",
        "why do hotels ask for a deposit",
        "what's the difference between broth and stock",
        "why does my phone get hot when charging",
        "how do libraries decide which books to buy",
        "why are eggs sold refrigerated here but not in europe",
        "what does pre-approved actually mean for a loan",
        "why do knees crack when you squat",
        "how does jury duty selection work",
        "why is wifi slower far from the router",
        "what's the point of a homeowners association",
        "why do gas prices end in nine tenths of a cent",
        "how do tides work",
        "why does traffic jam up with no accident in sight",
"why does bread get stale faster in the fridge",
        "what's the difference between a co-op and a condo",
        "how do plants know which way is up",
        "why do we get goosebumps",
        "what actually happens when you declare bankruptcy",
        "how does a French press differ from drip coffee",
        "why are tires black",
        "what's the difference between a notary and a lawyer",
        "how do fireflies make light",
        "why does my voice sound different on recordings",
        "what does escrow mean when buying a house",
        "how do self-cleaning ovens work",
        "why is it cheaper to fly on tuesdays",
        "what's the difference between mass and weight",
        "how do movie theaters make money if tickets go to studios",
"explain how a 401k works",
        "what's the difference between RAM and storage",
        "why do leaves change color in the fall",
        "how does wifi actually reach my phone",
        "explain interest rates like I'm new to this",
        "what's the deal with electric car batteries degrading",
        "why is the ocean salty",
        "how do credit cards make money",
        "what happens when you delete a file",
        "explain how airplanes stay up",
        "what's the difference between soccer and football rules",
        "why do we dream",
        "how does a dishwasher clean better than hand washing",
        "explain what APR means on a loan",
        "what's the difference between whiskey and bourbon",
        "why does my phone battery die faster in winter",
        "how do search engines decide what comes first",
        "what is gluten and why do some people avoid it",
        "suggest a good beginner camera and explain why",
        "what should I know before adopting a rescue dog",
        "Explain how a heat pump works and why it's more efficient than a furnace.",
        "What's the difference between a Roth IRA and a traditional IRA?",
        "Why is the sky blue during the day but red at sunset?",
        "Explain quantum entanglement like I'm twelve.",
        "How does compound interest actually work?",
        "What causes inflation and who benefits from it?",
        "Walk me through how vaccines train the immune system.",
        "Why do some countries drive on the left?",
        "Explain what happens during a solar eclipse.",
        "How do noise-cancelling headphones work?",
        "What's the deal with daylight saving time — why do we still do it?",
        "Explain the difference between weather and climate.",
        "How is olive oil graded, and what does extra virgin mean?",
        "Why can't we just print more money to pay off national debt?",
        "What does it mean when the Fed raises interest rates?",
        "Explain how DNS resolves a website name to an address.",
        "Why do airplanes leave white trails in the sky?",
        "What's the difference between bail and bond?",
        "How do bees decide where to build a hive?",
        "Explain the electoral college in plain terms.",
    ],
    "reasoning": [
"order these six chores to finish everything fastest, show the logic",
        "plan the optimal route for these deliveries and explain the ordering",
"design a multi-tenant rate limiter with per-tenant SLAs and explain the fairness tradeoffs",
        "sketch a lock-free eviction scheme and justify the memory-ordering choices",
        "explain how you'd mitigate ABA in a concurrent stack for a high-traffic service",
        "design cache eviction for a shared inference service and defend the policy under contention",
"argue it out for me: keep the office or go fully remote",
        "was the rebrand worth it, look at these numbers with me",
        "is it worth switching suppliers mid-year, weigh it",
        "one senior hire or two juniors, make the case both ways",
        "did raising prices pay off, walk through the impact",
"architect a lock-free ring buffer and walk through the memory fences",
        "design a wait-free counter for a busy gateway and explain the contention tradeoffs",
"design a concurrent cache and explain the memory ordering tradeoffs",
        "choose between managed and self-hosted postgres for us and defend it",
        "pick the better of these two vendor quotes and justify the choice",
        "should we shard now or scale vertically another year, argue it",
        "explain the ABA problem and how you'd mitigate it in our queue",
        "decide between the two job offers assuming equity is illiquid",
"help me decide between fixing my old laptop or buying new, it's a 6 year old macbook",
        "we've got 4 days in portugal, split them between lisbon and porto sensibly",
        "figure out if hosting thanksgiving or traveling makes more sense this year",
        "my side project makes 300 a month, is it worth incorporating",
        "reason through whether to take the settlement or go to trial with these facts",
        "help me pick between the gym near work and the cheaper one near home",
        "our team of 5 has 3 on-call shifts, design a fair rotation",
        "should I batch cook sundays or meal-kit, given my schedule",
        "walk through whether upgrading insulation beats replacing the furnace",
        "decide if we should drive or fly for a 500 mile trip with a toddler",
"design a rate limiter for a multi-region API and walk through the tradeoffs",
        "sketch the architecture for a ticketing system that survives a flash sale",
        "how would you shard a social graph, reason through the options",
        "design an idempotent payment retry scheme and justify each choice",
        "propose a caching strategy for a personalized news feed and defend it",
        "reason through exactly-once versus at-least-once for our order pipeline",
        "design a schema for versioned documents with cheap rollback, explain why",
        "how should we partition a time-series store for both recent and historical reads",
        "argue for or against event sourcing for a small inventory service",
        "design a deduplication approach for a webhook consumer under retries",
        "plan a zero-downtime database migration for a renamed column, step by step",
        "reason about consistency choices for a collaborative text editor",
        "design a fair job scheduler for mixed short and long tasks, explain the policy",
        "how would you detect and break a distributed deadlock here, think it through",
        "propose a backpressure strategy for a bursty ingest pipeline and justify it",
"help me plan a birthday party for 20 kids on a budget",
        "which phone should I upgrade to, I mostly take photos",
        "give me honest feedback on my pricing strategy",
        "help me decide between these two apartment options",
        "plan my training schedule for a half marathon in 12 weeks",
        "what's the best order to visit these 5 cities by train",
        "help me figure out if freelancing full time makes sense",
        "which credit card fits my spending, mostly groceries and travel",
        "map out a savings plan to hit 20k in two years",
        "advise me on whether to repair or replace my 12 year old car",
        "Should I lease or buy a car if I drive 25k miles a year? Walk through the math.",
        "Compare living in Austin vs Denver for a remote software engineer with two kids.",
        "Which is the better deal: a 15-year mortgage at 5.1% or 30-year at 5.8%? Reason it out.",
        "Help me think through whether to take the job offer with more pay but worse equity.",
        "My startup has 8 months of runway. Should we raise now or cut burn? Lay out the tradeoffs.",
        "Compare PostgreSQL and DynamoDB for an event-sourced ordering system under spiky load.",
        "Is it smarter to pay off my 6% student loans or invest in index funds? Show the reasoning.",
        "Plan the seating for a 12-person dinner where three pairs of guests can't sit together.",
        "A train leaves at 3pm going 80 km/h; another at 4pm going 110 km/h. When does the second catch up?",
        "Weigh the pros and cons of microservices vs a modular monolith for a 6-person team.",
        "If I flip a fair coin five times, what's the probability of at least two heads? Explain.",
        "Should our family of four get the annual theme park pass or pay per visit? We might go 5 times.",
        "Analyze whether it's worth switching from AWS to a bare-metal provider at our scale.",
        "Compare the total cost of ownership of an EV vs a hybrid over 8 years in a cold climate.",
        "Decide the optimal order to pay down these four debts and justify the strategy.",
        "Three friends split a bill with a coupon and unequal orders — figure out who owes what.",
        "Evaluate whether our SaaS should move from per-seat to usage-based pricing.",
        "Which apartment should I pick: cheaper with a 50-minute commute, or pricier 10 minutes away?",
        "Reason through whether a 4-day work week would raise or lower our team's output.",
        "Given these symptoms and constraints, which project management method fits our team best?",
    ],
    "code": [
"add caching to the public api",
        "add retry logic to the sync endpoint",
        "add input validation to the upload route",
        "the scheduled job stopped writing output, dig into why",
        "the backup task silently fails at 2am, look at the code",
"build a website for my flower shop",
        "make a site for my barbershop with online booking",
        "build a booking site for my nail salon",
        "put up a simple website for our diner",
        "build a website for my tutoring business",
        "make a website for the family farm stand",
"wire the payment provider into our signup flow",
        "hook the analytics SDK into the mobile app",
        "integrate the search service with the product catalog",
        "connect the form submissions to our CRM",
        "our checkout keeps erroring on submit, debug it",
        "the cart total comes out wrong after applying coupons, fix the calculation",
        "explain what this module does and tidy it up",
        "walk through this script and suggest refactors",
        "read through parser.py and tell me what could break",
        "the nightly job writes duplicates, trace the logic and fix it",
        "plug single sign-on into the admin panel",
        "add webhooks so orders sync to the warehouse system",
"the stack trace is pasted below, tell me what's crashing",
        "logs attached, why is the worker restarting every 5 minutes",
        "attached the failing CI output, make the build green",
        "here's the error output pasted in, fix the import cycle",
        "core dump attached, where is the null deref",
        "pasted the diff below, spot the regression",
        "the k8s events are attached, why won't the pod schedule",
        "attached my docker-compose file, the volumes aren't mounting",
        "pasted the SQL and the explain plan, speed this query up",
        "screenshot of the console errors attached, fix the page",
        "the panic log is pasted here, find the race",
        "attached the nginx config, redirects are looping",
"create a splash page for our app launch next month",
        "build the marketing site for my consulting practice",
        "spin up a coming-soon page with an email capture",
        "make a landing page for the charity 5k with a signup button",
        "put together a one-page site for our food truck's launch",
        "create a product page with a buy button for my ebook",
        "build a promo page for the album release with an embedded player",
        "make the launch page responsive and add the countdown",
        "create a simple storefront page for my prints",
        "build a signup page for the beta and wire it to a spreadsheet",
        "make a teaser page for the podcast launch",
        "create an event page with schedule, map, and RSVP form",
"why doesn't my program compile, error log below",
        "the tests in this repo keep failing, figure out why",
        "debug this stack trace for me",
        "my script crashes with a segfault, here's the code",
        "refactor this function so it's actually readable",
        "explain what this regex does and simplify it",
        "the build passes locally but fails in CI, investigate",
        "there's a memory leak somewhere in this service, find it",
        "add error handling to this endpoint",
        "why is this query so slow, here's the schema",
        "convert this callback code to async await",
        "the login form throws a 500 on submit, fix it",
        "write unit tests for the parser module",
        "this loop is off by one somewhere, spot it",
        "migrate this component from class to hooks",
        "my docker container exits immediately, diagnose it",
        "clean up the linter warnings in this file",
        "the app works in chrome but breaks in safari, why",
        "optimize this function, it's called a million times",
        "hook up the payment webhook to update order status",
        "Make me a simple app to track my workouts.",
        "Create a landing page with a signup form for my newsletter.",
        "I want an online store for my handmade candles, set it up.",
        "Build a portfolio site for my photography, dark theme.",
        "Set up a blog where I can post recipes with photos.",
        "Make a Chrome extension that hides YouTube comments.",
        "Create a Discord bot that welcomes new members.",
        "I need a booking page where clients can pick a time slot with me.",
        "Build a dashboard showing our sales numbers from this spreadsheet.",
        "Write a script that renames all my vacation photos by date.",
        "Automate downloading my bank statements every month.",
        "Make a tool that converts CSV files to pretty HTML tables.",
        "Set up a Telegram bot that sends me the weather every morning.",
        "Create a countdown timer page for our product launch.",
        "Build a quiz app for my classroom with a leaderboard.",
        "I want a personal finance tracker with charts, can you build it?",
        "Make my restaurant a menu page with prices I can edit easily.",
        "Fix my landing page, the hero image overlaps the text on mobile.",
        "Add a dark mode toggle to my existing site.",
    ],
    "tool_use": [
"order two more boxes of the usual printer paper",
        "text the electrician that the outlet sparks",
        "message the landlord about the broken gate",
        "reorder the coffee pods we got last month",
"reschedule the standup to 9:30 and notify the channel",
        "order a replacement filter for the office air purifier",
        "set a recurring transfer of 200 to savings on payday",
        "dim the porch lights at sunset every day",
        "add the dentist appointment to the family calendar",
        "renew the domain before it lapses next week",
        "send the signed contract back to the agency",
        "book a window seat on the earlier flight if one opens",
        "log 8 hours against the Henderson project for yesterday",
        "mute the group chat until monday morning",
        "submit the timesheet and cc my manager",
        "print the shipping labels for today's orders",
        "top up the transit card with 20 dollars",
        "archive last quarter's invoices to the shared drive",
        "start the robot vacuum in the kitchen only",
        "Book me a table for two at an Italian place near the office on Friday at 7.",
        "Add milk, eggs, and coffee beans to my shopping list.",
        "Schedule a 30-minute sync with the design team next Tuesday morning.",
        "Set a reminder to renew my passport in March.",
        "Send the Q3 deck to the leadership channel at 9am tomorrow.",
        "Cancel my 2pm and move the dentist appointment to Thursday.",
        "Order another box of the printer paper we got last time.",
        "Turn off the living room lights and set the thermostat to 68.",
        "Play my focus playlist and silence notifications for two hours.",
        "File an expense for the client dinner receipt I just uploaded.",
        "Create a Jira ticket for the login timeout bug and assign it to Priya.",
        "Text my wife that I'll be 20 minutes late.",
        "Find the cheapest nonstop flight to Chicago next weekend and hold it.",
        "Start a timer for 25 minutes.",
        "Add this article to my read-later list.",
        "Open a pull request with these changes and request review from the platform team.",
    ],
    "translation": [
"render this menu into Korean",
        "render the captions into Japanese for the trailer",
"translate this safety data sheet into Czech",
        "put the spec sheet into French for the distributor",
"put this instruction leaflet into Polish",
        "put the welcome letter into Ukrainian",
        "put these captions into Korean for the app store",
        "turn this english slogan into natural sounding Italian",
        "render the safety card into Spanish and Haitian Creole",
        "put my grandmother's blessing into English from Yiddish",
"translate this care-instructions tag into Dutch and Swedish",
        "how do you say 'is this seat taken' in Portuguese",
        "translate my aunt's recipe card from Hungarian",
        "put these museum captions into simplified Chinese",
        "translate the parent newsletter into Somali and Arabic",
        "render this poem from Farsi into English, keep the imagery",
        "what's 'out of order' in German, for a sign",
        "translate our cancellation policy into Greek",
        "convert this voicemail transcript from Russian to English",
        "localize these onboarding tooltips into French Canadian",
        "translate the allergy warning into Japanese for the menu",
        "how would you say 'long time no see' naturally in Mandarin",
        "translate this folk song verse from Gaelic",
        "put the safety briefing into Tagalog",
        "translate my toast into Hebrew for the bar mitzvah",
        "Translate this product description into French and German.",
        "How do you say 'where is the nearest pharmacy' in Japanese?",
        "Translate my grandmother's letter from Polish to English, keep the tone.",
        "Localize this error message into Spanish, Portuguese, and Italian.",
        "Translate the chorus of this song from Korean to English.",
        "Convert this legal disclaimer into simplified Chinese.",
        "Translate this restaurant menu from Thai to English.",
        "What's the German word for the feeling of wanting to be alone?",
        "Translate our onboarding email into Hindi without sounding stiff.",
        "Render this medieval Latin inscription into modern English.",
        "Translate these UI strings to Arabic and flag any that will overflow.",
        "Say 'thank you for your hospitality' in Turkish, formal register.",
        "Translate this WhatsApp conversation from Brazilian Portuguese.",
        "Put this safety notice into Vietnamese and Tagalog.",
    ],
    "rag": [
"according to the included policy, how many vacation days accrue per month",
        "using only this warranty text, who covers return shipping",
        "from the pasted release notes, when did the export format change",
        "per the provided handbook, can unused sick days roll over",
"from the pasted API changelog, which version dropped basic auth",
        "per the attached swagger file, which endpoints need an admin token",
        "using the provided SDK docs, how do I paginate results",
        "based on the pasted schema reference, which fields are nullable",
"per the attached employee handbook, what counts as a reimbursable expense",
        "using the pasted product FAQ, does the blender ship with a travel lid",
        "from the provided inspection report, which items failed",
        "based on the included terms, can I transfer my ticket to a friend",
        "according to the pasted job description, is the role hybrid or remote",
        "using the attached datasheet, what's the operating temperature range",
        "from the provided court opinion, what standard of review applied",
        "per the included HOA rules, are window AC units allowed",
        "based on the attached migration guide, which endpoints are deprecated",
        "using the pasted study methods section, how were participants recruited",
        "from the included press release, when does the acquisition close",
        "per the provided menu, which mains are gluten free",
        "according to the attached warranty card, is water damage covered",
        "using the pasted meeting agenda, who presents the budget item",
        "from the provided README, what ports does the container expose",
        "based on the included survey results, what was the response rate",
        "per the attached zoning letter, can the lot be subdivided",
        "using the provided rubric, what earns full marks on clarity",
        "from the pasted incident report, what was the root cause",
        "according to the included itinerary, which day is the cooking class",
        "based on the provided spec, what's the maximum payload size",
        "per the attached bylaws, how many members make quorum",
        "using the included changelog, when was dark mode added",
        "from the pasted operating manual, how do I reset to factory settings",
        "based on the attached contract rider, what does the venue provide",
        "per the provided benefits summary, when does dental coverage start",
        "using the attached lab results, is the iron level in range",
        "from the included policy memo, who approves exceptions",
        "based on the pasted user guide, can two accounts share a library",
        "per the provided estimates, which contractor included permits",
        "using the attached floor plan notes, which walls are load bearing",
        "from the included appendix, what were the exclusion criteria",
        "based on the pasted timetable, is there a direct train after 9pm",
        "per the attached grant guidelines, are stipends an allowable cost",
        "using the provided troubleshooting matrix, what does code E4 mean",
        "from the included maintenance log, when were the brakes last serviced",
        "based on the attached charter, can the committee meet remotely",
        "per the pasted schema docs, which fields are required on create",
        "using the included style guide, how are dates formatted in headlines",
        "from the provided onboarding doc, which trainings are due in week one",
"Given the wiki pages pasted below, when was the bridge actually completed?",
        "Answer using only the provided excerpts: what triggers the circuit breaker in this system?",
        "Based on the terms of service above, can users export their data after cancellation?",
        "From the pasted changelog entries, which release introduced the rate limiter?",
        "Using the context documents, list the prerequisites for the certification exam.",
        "Per the attached lease agreement, who is responsible for appliance repairs?",
        "According to the onboarding guide above, what accounts do new hires get by default?",
        "From the grant proposal text provided, what is the total requested budget?",
        "Based on these API docs, what does error code 4092 mean and how do I recover?",
        "Using the syllabus below, which weeks cover thermodynamics?",
        "Answer strictly from the given financial statements: what was the operating margin?",
        "According to the pasted troubleshooting guide, what should I check before replacing the pump?",
        "From the provided clinical guidelines, what is the recommended dosage for adults over 65?",
        "Based on the meeting transcript above, who volunteered to own the migration?",
        "Using the provided style guide, how should we capitalize product names in headings?",
        "Per the security policy document, how often must access reviews happen?",
        "From these customer emails, what date did the outage reportedly start?",
        "According to the manual excerpt, what does the blinking amber light indicate?",
        "Answer from the given research abstracts only: which study had the largest sample size?",
        "Based on the pasted itinerary, how long is the layover in Doha?",
        "Using the FAQ content above, is there a fee for early withdrawal?",
        "From the codebase README provided, what environment variables are required to boot?",
        "Using the attached policy documents, what is our parental leave allowance?",
        "Based on the knowledge base articles below, how do I rotate the API keys?",
        "According to these meeting minutes, what did we decide about the vendor contract?",
        "From the documentation provided, explain how to configure SSO with Okta.",
        "Answer from the context only: what were the side effects reported in the trial?",
        "Given these three support articles, why would the sync fail on mobile?",
        "Using the employee handbook excerpt, can I carry over unused vacation days?",
        "Based on the product spec below, does the device support USB-C charging?",
        "From these earnings transcripts, what guidance did management give for Q4?",
        "Consult the attached runbook and tell me the rollback steps for a bad deploy.",
        "According to this insurance policy text, is water damage from a burst pipe covered?",
        "Using only the provided court filings, summarize the plaintiff's main claim.",
    ],
    "other": [
"you there",
        "hello hello",
        "go ahead then",
        "why'd you stop",
        "come again",
        "one more",
        "test 123 test",
        "placeholder lorem text ipsum",
        "undo",
        "redo",
        "per my last note",
        "as per my previous email",
        "did you get that",
        "still with me",
        "hold that thought",
"🚀🚀",
        "ok ok ok ok",
        "b33f cafe 0101",
        "wibble wobble flooble",
        "yes no maybe so",
        "blah blah blah",
        "foo bar baz qux",
        "hmm hmm hmm",
"jkjkjk",
        "asdfgh lkjh",
        "zzzzzz",
        "testing 123",
        "just testing this",
        "sample text sample text",
        "ipsum lorem placeholder here",
        "deadbeef 1234",
        "a1b2c3d4e5f6",
        "keep it coming",
        "and?",
        "then what",
        "carry on",
        "once more",
        "hold on",
        "never mind that",
        "forget I asked",
        "one more time",
        "do it over",
        "too plain",
        "jazz it up",
        "more punch",
        "less wordy",
        "like the last one",
        "same as yesterday's",
        "the earlier version",
        "the one before that",
        "scratch that",
        "start over",
        "from the top",
"ok",
        "sure",
        "yep do that",
        "sounds good to me",
        "go ahead",
        "one sec",
        "brb",
        "back now",
        "still thinking",
        "give me a minute",
        "not that one",
        "the second option",
        "like I said before",
        "as above",
        "keep going",
        "more please",
        "again",
        "another one",
        "next",
        "shorter",
        "longer",
        "simpler",
        "fancier",
        "less of that",
        "hm not quite",
        "closer",
        "almost",
        "eh",
        "meh",
        "act like a grumpy chef judging my sandwich",
        "pretend we're on a cooking show",
        "be the narrator of my morning routine",
        "roleplay a landlord ignoring my calls",
        "you're the genie, I found the lamp",
        "let's improvise a scene in a lighthouse",
        "talk like a cowboy for a bit",
        "be my hype man for this presentation",
        "pretend to be my plant and tell me how you feel",
        "interview me like I'm famous",
        "howdy",
        "yo",
        "sup",
        "morning",
        "night night",
        "thanks a bunch",
        "appreciate it",
        "you rock",
        "my bad",
        "no rush",
        "wow really",
        "no way",
        "seriously?",
        "huh interesting",
        "wild",
        "asdf",
        "qwerty test",
        "12345",
        "xxxxx",
        "0x00ff riddle nonsense",
"act as a medieval innkeeper and greet me",
        "pretend to be a grumpy weather forecaster",
        "roleplay a job interview where you're the candidate",
        "be my improv partner, we're stranded on the moon",
        "act like a 1920s radio announcer for this game recap",
        "pretend you're my personal trainer yelling encouragement",
        "let's play twenty questions",
        "you be the dungeon master, I'm a rogue",
        "act as a french waiter taking my order",
        "pretend to interview me like a talk show host",
        "speak like shakespeare for the rest of this chat",
        "be a devil's advocate against my plan",
        "hey how's it going",
        "good morning!",
        "thanks, that was helpful",
        "lol that's actually funny",
        "are you a real person?",
        "what should we talk about",
        "tell me something interesting",
        "I'm bored",
        "never mind, forget it",
        "ok sounds good",
        "wow",
        "can you keep a secret",
        "what do you think about me",
        "let's play a game",
        "sing me something",
        "do you ever get tired",
    ],
}
